'use strict';

const http = require('http');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const TARGET = String(process.env.DASHBOARD_URL || '').replace(/\/+$/, '');
const WORK_DIR = process.env.RUNNER_WORK_DIR || '/runner-work';
const PORT = Math.max(1024, Math.min(Number(process.env.NODE_LOCAL_PROXY_PORT || 18790), 65535));
const MAX_BODY = 4 * 1024 * 1024;
let child = null;
let stopping = false;

if (!/^https?:\/\//i.test(TARGET)) { console.error('ERROR: workload proxy requires DASHBOARD_URL'); process.exit(1); }

function parseRunnerConsole(text){text=String(text||'');let running=null,completedAtIndex=-1,m;const runRe=/(?:^|\n)(\d{4}-\d{2}-\d{2}[ T][0-9:]+Z):\s*Running job:\s*(.+?)\s*(?=\n|$)/g;const doneRe=/(?:^|\n)(\d{4}-\d{2}-\d{2}[ T][0-9:]+Z):\s*Job\s+(.+?)\s+completed with result:/g;while((m=runRe.exec(text)))running={job:m[2].trim().slice(0,240),started_at:new Date(m[1].replace(' ','T')).toISOString(),index:m.index};while((m=doneRe.exec(text)))completedAtIndex=m.index;return{job:running?.job||'',started_at:running?.started_at||null,locally_busy:Boolean(running&&running.index>completedAtIndex)}}
async function newestRepository(){const root=path.join(WORK_DIR,'_PipelineMapping');let best=null;const stack=[root];let visited=0;while(stack.length&&visited<2000){const dir=stack.pop();let entries;try{entries=await fs.promises.readdir(dir,{withFileTypes:true})}catch{continue}for(const entry of entries){if(++visited>2000)break;const full=path.join(dir,entry.name);if(entry.isDirectory()){stack.push(full);continue}if(!entry.isFile()||entry.name!=='PipelineFolder.json')continue;try{const stat=await fs.promises.stat(full);const json=JSON.parse(await fs.promises.readFile(full,'utf8'));const repo=String(json.RepositoryName||'').trim();const lastRun=Date.parse(json.LastRunOn||'');const when=Number.isFinite(lastRun)?lastRun:stat.mtimeMs;if(repo&&(!best||when>best.when))best={repo,when}}catch{}}}return best?{repo:best.repo,last_run_at:new Date(best.when).toISOString()}:{repo:'',last_run_at:null}}
async function detectWorkload(body){const local=parseRunnerConsole(body?.log_tail||'');const repo=await newestRepository();const active=body?.runner_busy===true||(body?.runner_busy==null&&local.locally_busy);return{active,repository:active?repo.repo:'',job:active?local.job:'',started_at:active?local.started_at:null,repository_last_run_at:active?repo.last_run_at:null,source:'runner-local',confidence:repo.repo&&local.job?'high':(repo.repo||local.job?'medium':'low'),detected_at:new Date().toISOString()}}
function readRequest(req){return new Promise((resolve,reject)=>{let total=0;const chunks=[];req.on('data',chunk=>{total+=chunk.length;if(total>MAX_BODY){reject(new Error('request too large'));req.destroy();return}chunks.push(chunk)});req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)})}
async function postWorkload(headers,nodeId,runnerName,workload,runnerBusy){try{await fetch(`${TARGET}/internal/nodes/workload`,{method:'POST',headers:{authorization:String(headers.authorization||''),'content-type':'application/json','user-agent':'neko-node-workload-proxy/1.0'},body:JSON.stringify({node_id:nodeId,runner_name:runnerName,runner_busy:runnerBusy,workload})})}catch(err){console.warn(`[workload] report failed: ${err.message}`)}}

const server=http.createServer(async(req,res)=>{try{const bodyBuffer=await readRequest(req);let forwardBody=bodyBuffer,heartbeat=null,workload=null;const pathname=new URL(req.url,'http://127.0.0.1').pathname;if(pathname==='/internal/nodes/heartbeat'&&req.method==='POST'){try{heartbeat=JSON.parse(bodyBuffer.toString('utf8')||'{}');workload=await detectWorkload(heartbeat);if(heartbeat.runner_busy==null&&typeof workload.active==='boolean')heartbeat.runner_busy=workload.active;forwardBody=Buffer.from(JSON.stringify(heartbeat))}catch(err){console.warn(`[workload] heartbeat parse: ${err.message}`)}}const targetUrl=`${TARGET}${req.url}`;const headers={...req.headers};delete headers.host;delete headers['content-length'];const upstream=await fetch(targetUrl,{method:req.method,headers,body:['GET','HEAD'].includes(req.method)?undefined:forwardBody,redirect:'manual'});const responseBody=Buffer.from(await upstream.arrayBuffer());const responseHeaders={};for(const[k,v]of upstream.headers.entries())if(!['transfer-encoding','content-encoding','content-length','connection'].includes(k.toLowerCase()))responseHeaders[k]=v;responseHeaders['content-length']=String(responseBody.length);res.writeHead(upstream.status,responseHeaders);res.end(responseBody);if(heartbeat&&workload)setImmediate(()=>postWorkload(req.headers,heartbeat.id,heartbeat.runner_name,workload,heartbeat.runner_busy))}catch(err){console.error(`[workload-proxy] ${req.method} ${req.url}: ${err.message}`);if(!res.headersSent)res.writeHead(502,{'content-type':'application/json'});res.end(JSON.stringify({error:'node workload proxy failed'}))}});
function startSupervisor(){child=spawn(process.execPath,['/app/supervisor.js'],{stdio:'inherit',env:{...process.env,DASHBOARD_URL:`http://127.0.0.1:${PORT}`}});child.once('exit',(code,signal)=>{child=null;if(!stopping){console.error(`[workload-proxy] supervisor exited code=${code} signal=${signal||'none'}`);process.exit(code||1)}})}
function stop(signal){if(stopping)return;stopping=true;console.log(`[workload-proxy] ${signal}: stopping`);if(child)child.kill('SIGTERM');server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),6000).unref()}
server.listen(PORT,'127.0.0.1',()=>{console.log(`[workload-proxy] local heartbeat proxy on 127.0.0.1:${PORT}; runner work=${WORK_DIR}`);startSupervisor()});
process.once('SIGTERM',()=>stop('SIGTERM'));process.once('SIGINT',()=>stop('SIGINT'));process.once('SIGHUP',()=>stop('SIGHUP'));
